# Generated by Django 5.2.12 on 2026-03-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Contact',
        ),
    ]
